version: '3.4'

services:
  client:
    container_name: client-monitoring-example
    hostname: demo-client
    image: ${DOCKER_REGISTRY-}client-monitoring-example
    build:
      context: .
      dockerfile: RemoteLoggingBlazorExample/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
    ports:
        - 8082:80
    depends_on:
        prometheus:
            condition: service_healthy
        grafana:
            condition: service_healthy
    
  grafana:
    container_name: grafana-monitoring-example
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
        - ./docker-compose-setup-files/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - ./docker-compose-setup-files/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
        prometheus:
            condition: service_healthy
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3000/
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitoring-example
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./docker-compose-setup-files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:9090/
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s
  
  loki:
    command: -config.file=/etc/loki/local-config.yaml
    image: grafana/loki
    ports:
      - mode: ingress
        protocol: tcp
        published: 3100
        target: 3100
      - mode: ingress
        protocol: tcp
        published: 9095
        target: 9095
    volumes:
      - source: loki
        target: /loki
        type: volume
volumes:
  loki: ~