{
 "title": "Custom values",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(order_value_usd_bucket[$__interval])) by (le)"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jobs_queued{instance=\"host.docker.internal:8082\"}"
    }
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jobs_processed_total{instance=\"host.docker.internal:8082\"}"
    }
   ]
  }
 ]
}